# Generated by Django 5.2.1 on 2025-05-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_id'),
        ('patients', '0004_alter_patient_id'),
    ]

    operations = [
    ]
